bookshelf/bookshelf/book/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('add-book/', views.CreateBookView.as_view(), name='add-book'),
    path('books-by-genre/<str:genre>/', views.BooksByGenreView.as_view(), name='books-by-genre'),
    path('<int:id>/', include([
        path('book-details/', views.BookDetailsView.as_view(), name='book-details'),
        path('change_status/', views.UpdateBookStatusView.as_view(), name='book-status'),
        path('edit_book/', views.EditBookView.as_view(), name='edit-book'),
        path('delete_book/', views.DeleteBookView.as_view(), name='delete-book'),
        path('mybookshelf/', views.MyBookShelfView.as_view(), name='mybookshelf'),
        ])),
] + [
    path('api/', views.BookListApiView.as_view(), name='book_list_api'),
]

bookshelf/bookshelf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookshelf.common.urls')),
    path('book/', include('bookshelf.book.urls')),
    path('author/', include('bookshelf.author.urls')),
    path('accounts/', include('bookshelf.accounts.urls')),
]

bookshelf/bookshelf/book/models.py
from django.core.validators import MaxLengthValidator
from django.db import models
from django.db.models import Avg
from bookshelf.accounts.models import CustomerModel
from bookshelf.author.models import Author
from .validators import UpperValueValidator
from .choices import GenreChoices, BookStatusChoices


# Create your models here.

class Book(models.Model):
    user = models.ForeignKey(
        to=CustomerModel,
        blank=False,
        null=False,
        on_delete=models.CASCADE,
        related_name='books'
    )
    author = models.ForeignKey(
        to=Author,
        blank=False,
        null=False,
        on_delete=models.CASCADE,
        related_name='books'
    )
    picture_url = models.URLField(
        blank=False,
        null=False
    )
    description = models.TextField(
        validators=[MaxLengthValidator(2000), UpperValueValidator()],
        help_text="Not more than 2000 characters and first letter should be upper or in Book an allowed quotation symbol."
    )
    title = models.CharField(
        max_length=200,
        blank=False,
        null=False,
        unique=True
    )
    approved = models.BooleanField(
        default=False
    )
    genre = models.CharField(
        max_length=40,
        choices=GenreChoices.choices,
        default=GenreChoices.OTHERS
    )

    updated_at = models.DateTimeField(
        auto_now=True,
    )

    def __str__(self):
        return self.title

    def average_rating(self):
        curr_rating = f"{self.ratings.aggregate(Avg('rating'))['rating__avg']:.1f}" if self.ratings.aggregate(Avg('rating'))['rating__avg'] else None
        return curr_rating or 0

    def formatted_description(self):
        return self.description.replace('\n', '<br>')


class Comment(models.Model):
    book = models.ForeignKey(
        to=Book,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    user = models.ForeignKey(
        to=CustomerModel,
        on_delete=models.CASCADE,
        blank=False,
        null=False
    )
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment by {self.user.username} on {str(self.book)}"


class Rating(models.Model):
    book = models.ForeignKey(
        Book,
        on_delete=models.CASCADE,
        related_name='ratings'
    )
    user = models.ForeignKey(
        to=CustomerModel,
        on_delete=models.CASCADE
    )
    rating = models.PositiveIntegerField(choices=[(i, str(i)) for i in range(1, 6)])

    class Meta:
        unique_together = ('book', 'user')


class UserBookStatus(models.Model):
    user = models.ForeignKey(to=CustomerModel, on_delete=models.CASCADE, related_name="book_statuses")
    book = models.ForeignKey(to=Book, on_delete=models.CASCADE, related_name="user_statuses")
    status = models.CharField(
        max_length=50,
        choices=BookStatusChoices.choices,
        default=BookStatusChoices.NONE
    )

    class Meta:
        unique_together = ('user', 'book')
        verbose_name = "User Book Status"
        verbose_name_plural = "User Book Statuses"

    def __str__(self):
        return f"{self.user.username} status on book - {self.book.title}"

bookshelf/bookshelf/book/forms.py
from django import forms

from bookshelf.author.models import Author
from bookshelf.book.models import Book, Comment


class BaseBookForm(forms.ModelForm):
    class Meta:
        model = Book
        exclude = ['approved', 'user', 'updated_at']


class UpdateBookForm(BaseBookForm):
    class Meta(BaseBookForm.Meta):
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter the title of the book'
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 5,
                'placeholder': 'Enter a description (max 2000 characters)'
            }),
            'picture_url': forms.URLInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter the URL for the book picture'
            }),
            'genre': forms.Select(attrs={
                'class': 'form-select'
            }),
            'author': forms.Select(attrs={
                'class': 'form-select'
            }),
        }


class BaseCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']


class UpdateCommentForm(BaseCommentForm):
    text = forms.CharField(
        widget=forms.Textarea(
            attrs={'class': 'form-control'}
        ),
        required=True
    )


class DeleteCommentForm(BaseBookForm):
    text = forms.CharField(
        widget=forms.Textarea(
            attrs={'class': 'form-control'}
        ),
        required=True
    )


class CreateBookForm(BaseBookForm):
    author = forms.CharField(
        label="Author",
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter author’s full name (first and last name)'
        }),
        error_messages={
            'required': "You must provide the author's full name."
        }
    )

    class Meta(BaseBookForm.Meta):
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Title...'}),
            'genre': forms.Select(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'placeholder': 'Short description...'}),
            'picture_url': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Image url...'}),
        }

    def clean_author(self):
        author_name = self.cleaned_data.get('author')
        try:
            first_name, last_name = author_name.split(' ', 1)
            author = Author.objects.get(first_name=first_name, last_name=last_name)
        except (ValueError, Author.DoesNotExist):
            raise forms.ValidationError("The author's name must match exactly as it is in the YourBookShelf app.")
        return author

    def save(self, commit=True):
        book = super().save(commit=False)
        book.author = self.cleaned_data['author']
        if commit:
            book.save()
        return book

bookshelf/bookshelf/book/views.py
from asgiref.sync import sync_to_async
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from rest_framework.exceptions import NotFound
from rest_framework.views import APIView
from rest_framework.response import Response
from bookshelf.accounts.models import CustomerModel
from bookshelf.author.models import Author
from bookshelf.book.choices import BookStatusChoices
from bookshelf.book.forms import CreateBookForm, UpdateBookForm
from bookshelf.book.models import Book, UserBookStatus
from bookshelf.book.serializers import BookSerializer
from bookshelf.mixins import PermissionCheckMixin
from django.utils.html import escape


# Create your views here.


class CreateBookView(CreateView):
    template_name = 'book/add_book.html'
    model = Book
    form_class = CreateBookForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        if not form.is_valid():
            return self.form_invalid(form)

        form.instance.user = self.request.user
        return super().form_valid(form)


class BooksByGenreView(ListView):
    template_name = 'book/books_by_genre.html'
    context_object_name = 'books'

    def get_queryset(self):
        genre = self.kwargs['genre']
        return Book.objects.filter(genre=genre)


class BookDetailsView(DetailView):
    template_name = 'book/book_details.html'
    model = Book
    pk_url_kwarg = 'id'
    context_object_name = 'book'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        book = self.get_object()

        current_status = None
        if self.request.user.is_authenticated:
            user_status = UserBookStatus.objects.filter(user=self.request.user, book=book).first()
            current_status = user_status.status if user_status else None

        context['status_choices'] = BookStatusChoices.choices
        context['current_status'] = current_status

        return context


class UpdateBookStatusView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        book = get_object_or_404(Book, id=kwargs.get('id'))
        status = request.POST.get('status')

        if request.user.is_authenticated:
            user_status, created = UserBookStatus.objects.get_or_create(user=request.user, book=book)
            user_status.status = status
            user_status.save()

        return redirect('home')


class MyBookShelfView(LoginRequiredMixin, DetailView):
    model = CustomerModel
    pk_url_kwarg = 'id'
    template_name = 'book/mybookshelf.html'
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user = self.request.user

        context['status_choices'] = BookStatusChoices.choices

        return context


class EditBookView(LoginRequiredMixin, PermissionCheckMixin, UpdateView):
    template_name = 'book/update_book.html'
    pk_url_kwarg = 'id'
    model = Book
    form_class = UpdateBookForm

    def get_success_url(self):
        return reverse_lazy('book-details', kwargs={'id': self.object.id})


class DeleteBookView(LoginRequiredMixin, PermissionCheckMixin, DeleteView):
    template_name = 'book/delete_book.html'
    model = Book
    pk_url_kwarg = 'id'
    success_url = reverse_lazy('home')


class BookListApiView(APIView):

    def get(self, request):
        books = Book.objects.all()
        serializer = BookSerializer(books, many=True)
        return Response(serializer.data)

bookshelf/templates/book/add_book.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Book</title>
    {% include 'common/link.html' %}
    <link rel="stylesheet" href="{% static 'css/errors.css' %}">
    <link rel="stylesheet" href="{% static 'css/add-book.css' %}">
</head>
<body>
{% include 'common/nav.html' %}

<div class="container mt-5 book-card">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-sm">
                <div class="card-header bg-secondary text-white text-center">
                    <h5>Add New Book</h5>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_div }}

                        <div class="d-flex justify-content-center mt-3">
                            <button type="submit" class="btn btn-info px-4">Add Book</button>
                        </div>
                    </form>
                    <div class="container mt-5 text-center">
                        <p id="missing-content">Please make sure to enter the title first. Note that some information
                            may be missing if the title is not provided.</p>
                        <form id="wikiForm" class="mt-4">
                            <button type="submit" class="btn btn-primary">Generate Description</button>
                        </form>
                    </div>
                </div>

                <div class="card-footer text-center">
                    <a href="{% url 'home' %}" class="btn btn-secondary btn-sm">Cancel</a>
                </div>
            </div>
        </div>
    </div>
</div>


{% include 'common/footer.html' %}

<script src="{% static 'javascript/wikipedia_api_books.js' %}"></script>
</body>
</html>

bookshelf/templates/book/book_details.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    {% include 'common/link.html' %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
{% include 'common/nav.html' %}

<div class="container mt-5">
    <div class="card mb-4">
        <div class="card-body">
            <div class="row">
                <div class="col-md-4 d-flex justify-content-center align-items-center">
                    <img src="{{ book.picture_url }}" class="img-fluid rounded" alt="Book Image"
                         style="max-width: 100%; max-height: 200px; object-fit: cover;">
                </div>
                <div class="col-md-8">
                    <h5 class="card-title text-center">{{ book.title }}</h5>
                    <p class="text-center mb-2">
                        <small>
                            <a href="{% url 'author-details' book.author.id %}"
                               class="text-primary text-decoration-underline">
                                {{ book.author.get_full_name }}
                            </a>
                        </small>
                    </p>
                    <p class="card-text text-center">{{ book.formatted_description|safe }}</p>
                </div>
            </div>
        </div>
    </div>


    {% if user.is_authenticated %}
        <div class="card" style="margin-bottom: 100px">
            <div class="card-body">
                <h5 class="card-title text-center">Update Your Status For {{ book.title }}</h5>
                <form id="update-status-form" method="POST" action="{% url 'book-status' book.id %}" class="d-flex flex-column align-items-center">
                    {% csrf_token %}
                    <div class="text-center form-group w-100 mb-3">
                    <button type="submit" class="btn btn-secondary w-20">Save Status</button>
                        <label for="statusSelect" class="form-label">Select a Status:</label>
                        <select id="statusSelect" name="status" class="form-select">
                            {% for choice_value, choice_label in status_choices %}
                                <option value="{{ choice_value }}"
                                        {% if current_status == choice_value %}selected{% endif %}>
                                    {{ choice_label }}
                                </option>
                            {% endfor %}
                        </select>
                        {% if request.user == book.user %}
                            <a href="{% url 'edit-book' book.id %}" class="btn btn-secondary">Edit</a>
                            <a href="{% url 'delete-book' book.id %}" class="btn btn-danger">Delete</a>
                        {% endif %}
                    </div>
                </form>
            </div>
        </div>
    {% endif %}
</div>


{% include 'common/footer.html' %}
</body>
</html>

bookshelf/templates/book/books_by_genre.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Books By Genre</title>
    {% include 'common/link.html' %}
</head>
<body>
{% include 'common/nav.html' %}

<div class="container mt-5">
    {% for book in books %}
        {% if book.approved and book.author.approved %}
            <div class="card mb-4">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4 d-flex justify-content-center align-items-center">
                            <img src="{{ book.picture_url }}" class="img-fluid rounded" alt="Book Image"
                                 style="max-width: 100%; max-height: 200px; object-fit: cover;">
                        </div>

                        <div class="col-md-8 d-flex flex-column align-items-center justify-content-center">
                            <h5>{{ book.title }}</h5>
                            <small><a href="{% url 'author-details' book.author.id %}"
                                      class="text-primary text-decoration-underline">{{ book.author.get_full_name }}</a></small>
                            <p class="card-text mt-3 text-center">{{ book.description }}</p>
                        </div>

                    </div>
                </div>

                <div class="card-footer">
                    {% if book.genre != 'Others' %}
                        <h6>Genre: {{ book.genre }}</h6>
                    {% else %}
                        <h6>Genre: Not added</h6>
                    {% endif %}
                    <h6>Rating: {{ book.average_rating }}</h6>
                    <div class="rating mb-3">
                        <i class="fas fa-star" style="cursor: pointer;"></i>
                        <i class="fas fa-star" style="cursor: pointer;"></i>
                        <i class="fas fa-star" style="cursor: pointer;"></i>
                        <i class="fas fa-star" style="cursor: pointer;"></i>
                        <i class="fas fa-star" style="cursor: pointer;"></i>
                    </div>

                    <h6>Comments:</h6>
                    <ul class="list-group mb-3">
                        {% if book.comments.all %}
                            {% for comment in book.comments.all|dictsort:"created_at" %}
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    <div class="d-flex justify-content-between w-100">
                                        <div>
                                            <strong>{{ comment.user.username }}</strong>: {{ comment.text }}
                                        </div>

                                        <div class="d-flex align-items-center flex-column flex-md-row">
                                            {% if comment.user == user %}
                                                <div class="btn-group mb-2 mb-md-0">
                                                    <a href="{% url 'edit_comment' comment.id %}"
                                                       class="btn btn-sm btn-light">Edit</a>
                                                    <a href="{% url 'delete_comment' comment.id %}"
                                                       class="btn btn-sm btn-light">Delete</a>
                                                </div>
                                            {% endif %}
                                            <small class="text-muted mr-2">{{ comment.created_at }}</small>
                                        </div>
                                    </div>
                                </li>

                            {% endfor %}
                        {% else %}
                            <li class="list-group-item text-muted">No comments yet.</li>
                        {% endif %}
                    </ul>

                    {% if user.is_authenticated %}
                        <form method="post" action="{% url 'add_comment' book.id %}">
                            {% csrf_token %}
                            <div class="input-group">
                                <input type="text" name="text" class="form-control" placeholder="Add a comment"
                                       required>
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit">Comment</button>
                                </div>
                            </div>
                        </form>
                    {% else %}
                        <p><a href="{% url 'login' %}">Log</a> in to leave a comment.</p>
                    {% endif %}
                </div>
            </div>
        {% endif %}
    {% endfor %}
</div>


{% include 'common/footer.html' %}
</body>
</html>

bookshelf/templates/book/delete_book.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete Author</title>
    {% include 'common/link.html' %}
</head>
<body>
{% include 'common/nav.html' %}
    <div class="container mt-5">
        <div class="card">
            <div class="card-body text-center">
                <h4 class="card-title">Delete the Book</h4>
                <p class="card-text">Are you certain you want to delete the book ({{ book.title }})?</p>
                
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Yes, I'm sure.</button>
                    <a href="{% url 'book-details' book.id %}" class="btn btn-secondary">No, I don't want to.</a>
                </form>
            </div>
        </div>
    </div>

{% include 'common/footer.html' %}
</body>
</html>

bookshelf/templates/book/delete_comment.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete Comment</title>
    {% include 'common/link.html' %}
</head>
<body>
{% include 'common/nav.html' %}
    <div class="container mt-5">
        <div class="card">
            <div class="card-body text-center">
                <h4 class="card-title">Изтриване на коментар</h4>
                <p class="card-text">Сигурни ли сте, че искате да изтриете този коментар?</p>
                
                <form method="post" action="{% url 'delete_comment' comment.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Да, изтрий</button>
                    <a href="{% url 'home' %}" class="btn btn-secondary">Не, върни ме обратно</a>
                </form>
            </div>
        </div>
    </div>

{% include 'common/footer.html' %}
</body>
</html>

bookshelf/templates/book/edit_comment.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Comment</title>
    {% include 'common/link.html' %}
</head>
<body>
{% include 'common/nav.html' %}

<div class="container mt-5">
    <h2>Edit your comment</h2>

    <form method="post">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="id_text">Comment</label>
            {{ form.text }}
        </div>
        
        <button type="submit" class="btn btn-success">Save the changes</button>
        
        <a href="{% url 'home' %}" class="btn btn-secondary ml-2">Reject</a>
    </form>
</div>

{% include 'common/footer.html' %}
</body>
</html>

bookshelf/templates/book/mybookshelf.html
{% load static %}
{% load is_not_none %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Book Shelf</title>
    {% include 'common/link.html' %}
    <link rel="stylesheet" href="{% static 'css/errors.css' %}">
    <link rel="stylesheet" href="{% static 'css/add-book.css' %}">
</head>
<body>
{% include 'common/nav.html' %}

<div class="container mt-5">
    <div class="row">
        <!-- First Card: Your Uploaded Books -->
        <div class="col-12 mb-4">
            <div class="card shadow">
                <div class="card-header bg-secondary text-white">
                    <h5 class="card-title text-center">Your Uploaded Books</h5>
                </div>
                <div class="card-body">
                    {% if user.books.all %}
                        <ul class="list-group">
                            {% for book in user.books.all %}
                                <li class="list-group-item">
                                    <div class="d-flex align-items-center" style="margin-left: 20px">
                                        <img src="{{ book.picture_url }}" alt="Book Image" class="rounded me-3"
                                             style="width: 80px; height: 120px; object-fit: cover;">
                                        <div style="margin-left: 20px">
                                            <a href="{% url 'book-details' book.id %}">
                                                <strong style="color:black">{{ book.title }}</strong>
                                            </a><br>
                                            <small>by <a
                                                    href="{% url 'author-details' book.author.id %}">{{ book.author.get_full_name }}</a></small>
                                        </div>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p class="text-center text-muted">You haven't uploaded any books yet.</p>
                    {% endif %}
                </div>
            </div>
        </div>


        <div class="col-12 mb-4">
            <div class="card shadow">
                <div class="card-header text-white" style="background-color: lightslategrey">
                    <h5 class="card-title text-center">Books with Your Status</h5>
                </div>
                <div class="card-body">
                    {% if user.book_statuses.all and user.book_statuses.all|is_not_none %}
                        <ul class="list-group">
                            {% for status in user.book_statuses.all %}
                                <li class="list-group-item">
                                    <div class="d-flex align-items-center" style="margin-left: 20px">
                                        <img src="{{ status.book.picture_url }}" alt="Book Image" class="rounded me-3"
                                             style="width: 80px; height: 120px; object-fit: cover;">
                                        <div style="margin-left: 20px">
                                        <a href="{% url 'book-details' status.book.id %}">
                                                <strong style="color:black">{{ status.book.title }}</strong>
                                            </a><br>
                                            <small>Status: {{ status.get_status_display }}</small><br>
                                            <small>by <a
                                                    href="{% url 'author-details' status.book.author.id %}">{{ status.book.author.get_full_name }}</a></small>

                                            <form id="update-status-form" method="POST"
                                                  action="{% url 'book-status' status.book.id %}" class="mt-2">
                                                {% csrf_token %}
                                                <label for="statusSelect" class="form-label">Select a Status:</label>
                                                <div class="d-flex">
                                                    <select id="statusSelect" name="status" class="form-select me-2">
                                                        {% for choice_value, choice_label in status_choices %}
                                                            <option value="{{ choice_value }}"
                                                                    {% if current_status == choice_value %}selected{% endif %}>
                                                                {{ choice_label }}
                                                            </option>
                                                        {% endfor %}
                                                    </select>
                                                    <button type="submit" class="btn btn-secondary">Save Status</button>
                                                </div>
                                            </form>

                                        </div>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p class="text-center text-muted">You haven't added any statuses to books yet.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>



{% include 'common/footer.html' %}

</body>
</html>

bookshelf/templates/book/update_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Book</title>
    {% include 'common/link.html' %}
</head>
<body>
{% include 'common/nav.html' %}

<div class="container mt-5">
    <div class="card shadow-sm">
        <div class="card-header bg-secondary text-white">
            <h2 class="mb-0">Edit your book</h2>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}

                {{ form.as_p }}

                <div class="d-flex justify-content-end mt-4">
                    <button type="submit" class="btn btn-success me-2" style="margin-right: 1.5rem">Save the changes</button>
                    <a href="{% url 'book-details' book.id %}" class="btn btn-secondary">Reject</a>
                </div>
            </form>
        </div>
    </div>
</div>

{% include 'common/footer.html' %}
</body>
</html>