bookshelf/bookshelf/accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.CustomerLoginView.as_view(), name='login'),
    path('logout-confirmation/', views.logout, name='logout-page'),
    path('logout/', views.CustomerLogoutView.as_view(), name='logout'),
    path('register/', views.CustomerRegistrationView.as_view(), name='register'),
    path('<int:id>/details/', views.CustomerDetailsView.as_view(), name='account-details'),
    path('<int:id>/edit/', views.EditAccountView.as_view(), name='edit-account'),
    path('<int:id>/delete/', views.DeleteAccountView.as_view(), name='delete-account'),
]

bookshelf/bookshelf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookshelf.common.urls')),
    path('book/', include('bookshelf.book.urls')),
    path('author/', include('bookshelf.author.urls')),
    path('accounts/', include('bookshelf.accounts.urls')),
]

bookshelf/bookshelf/accounts/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models

from bookshelf.accounts.managers import CustomerManager


# Create your models here.


class CustomerModel(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(
        max_length=150,
        unique=True
    )
    email = models.EmailField(
        unique=True,
        blank=False,
        null=False
    )
    first_name = models.CharField(
        max_length=50,
        blank=True,
        null=True
    )
    last_name = models.CharField(
        max_length=50,
        blank=True,
        null=True
    )
    quiz_rating = models.IntegerField(
        default=0
    )
    picture_url = models.URLField(
        blank=True,
        null=True
    )

    is_active = models.BooleanField(
        default=True,
    )

    is_staff = models.BooleanField(
        default=False,
    )

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email"]

    objects = CustomerManager()

    def __str__(self):
        return self.username

bookshelf/bookshelf/author/models.py
from django.db import models
from bookshelf.accounts.models import CustomerModel
from .validators import UpperValueValidator


# Create your models here.


class Author(models.Model):
    first_name = models.CharField(
        max_length=100,
        null=False,
        blank=False,
        validators=[UpperValueValidator()]
    )
    last_name = models.CharField(
        max_length=100,
        null=False,
        blank=False,
        validators=[UpperValueValidator()]
    )
    date_of_birth = models.DateField(
        blank=False,
        null=False
    )
    bio = models.TextField(
        validators=[UpperValueValidator(message="Biography must start with an uppercase letter.")]
    )
    picture_url = models.URLField(
        blank=True,
        null=True
    )
    user = models.ForeignKey(
        to=CustomerModel,
        blank=False,
        null=False,
        on_delete=models.CASCADE
    )
    approved = models.BooleanField(
        default=False
    )

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    def formatted_bio(self):
        return self.bio.replace('\n', '<br>')

bookshelf/bookshelf/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from bookshelf.accounts.models import CustomerModel

UserModel = get_user_model()


class CustomerRegistrationForm(UserCreationForm):
    class Meta:
        model = UserModel
        fields = ('username', 'email', 'first_name', 'last_name')

    widgets = {
        'username': forms.TextInput(attrs={'class': 'form-control'}),
        'email': forms.EmailInput(attrs={'class': 'form-control'}),
        'first_name': forms.TextInput(attrs={'class': 'form-control'}),
        'last_name': forms.TextInput(attrs={'class': 'form-control'}),
        'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
        'password2': forms.PasswordInput(attrs={'class': 'form-control'}),
    }


class LoginForm(AuthenticationForm):
    def __init__(self, request=None, *args, **kwargs):
        super().__init__(request, *args, **kwargs)


class CustomerDetailsForm(forms.ModelForm):
    class Meta:
        model = CustomerModel
        exclude = ['is_active', 'is_staff', 'quiz_rating', 'password']

bookshelf/bookshelf/accounts/views.py
from django.contrib.auth import authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.contrib import messages

from bookshelf.accounts.forms import LoginForm, CustomerRegistrationForm, CustomerDetailsForm
from bookshelf.accounts.models import CustomerModel


# Create your views here.


class CustomerLoginView(LoginView):
    template_name = 'accounts/login.html'
    form_class = LoginForm

    def post(self, request, *args, **kwargs):
        form = self.get_form()

        if form.is_valid():
            return super().post(request, *args, **kwargs)
        else:
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)

            if user is None:
                messages.error(request, 'Invalid username or password.')

            return self.form_invalid(form)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))


class CustomerLogoutView(LogoutView, LoginRequiredMixin):
    template_name = 'accounts/logout.html'


def logout(request):
    return render(request, 'accounts/logout.html')


class CustomerRegistrationView(CreateView):
    form_class = CustomerRegistrationForm
    template_name = 'accounts/register.html'
    success_url = reverse_lazy('login')


class CustomerDetailsView(DetailView):
    model = CustomerModel
    template_name = 'accounts/account_details.html'
    pk_url_kwarg = 'id'
    context_object_name = 'customer'


class EditAccountView(LoginRequiredMixin, UpdateView):
    template_name = 'accounts/edit_account.html'
    pk_url_kwarg = 'id'
    model = CustomerModel
    form_class = CustomerDetailsForm

    def get_success_url(self):
        customer_id = self.object.id
        print(customer_id)
        return reverse_lazy('account-details', kwargs={'id': customer_id})


class DeleteAccountView(DeleteView):
    template_name = 'accounts/delete_account.html'
    pk_url_kwarg = 'id'
    model = CustomerModel
    success_url = reverse_lazy('home')

bookshelf/templates/accounts/account_details.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Account Details</title>
    {% include 'common/link.html' %}
    <link rel="stylesheet" href="{% static 'css/logout.css' %}">
</head>
<body>
{% include 'common/nav.html' %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mb-3 shadow-sm">
                <div class="row g-0">

                    <div class="col-md-4 d-flex align-items-center justify-content-center">
                        {% if customer.picture_url %}
                            <img src="{{ customer.picture_url }}"
                                 class="img-fluid rounded border border-secondary shadow-sm"
                                 alt="Customer Picture" style="max-width: 100%; max-height: 200px; object-fit: cover;">
                        {% else %}
                            <img src="{% static 'images/no-photo.gif' %}"
                                 class="img-fluid rounded border border-secondary shadow-sm"
                                 alt="No Picture Available"
                                 style="max-width: 100%; max-height: 200px; object-fit: cover;">
                        {% endif %}
                    </div>

                    <div class="col-md-8">
                        <div class="card-body">
                            {% if customer.first_name and customer.last_name %}
                                <h5 class="card-title">{{ customer.first_name }} {{ customer.last_name }}</h5>
                            {% elif customer.first_name %}
                                <h5 class="card-title">{{ customer.first_name }}</h5>
                            {% elif customer.last_name %}
                                <h5 class="card-title">{{ customer.first_name }}</h5>
                            {% else %}
                                <h5 class="card-title">No name added</h5>
                            {% endif %}
                        
                            <p class="card-text"><strong>Username:</strong> {{ customer.username }}</p>
                            <p class="card-text"><strong>Email:</strong> {{ customer.email }}</p>

                            {% if customer.quiz_results %}
                                <p class="card-text"><strong>Quiz Rating:</strong> {{ customer.quiz_results.points }}</p>
                                <p class="card-text"><strong>Level:</strong> {{ customer.quiz_results.level }}</p>
                            {% else %}
                                <p class="card-text"><strong>Quiz Rating:</strong>No information</p>
                                <p class="card-text"><strong>Level:</strong>No information</p>
                            {% endif %}

                            <div class="mt-3">
                                <a href="{% url 'edit-account' customer.id %}" class="btn btn-secondary">Edit</a>
                                <a href="{% url 'delete-account' customer.id %}" class="btn btn-danger">Delete</a>
                                <a href="{% url 'home' %}" class="btn btn-dark">Back</a>
                                {% if user.is_superuser or user.is_staff %}
                                <a href="{% url 'reports' %}" class="btn btn-warning">Reports</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% include 'common/footer.html' %}
</body>
</html>

bookshelf/templates/accounts/delete_account.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete Account</title>
    {% include 'common/link.html' %}
</head>
<body>
{% include 'common/nav.html' %}
    <div class="container mt-5">
        <div class="card">
            <div class="card-body text-center">
                <h4 class="card-title">Delete your account: {{ user.username }}</h4>
                <p class="card-text">Are you certain you want to delete your account?</p>
                
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Yes, I'm sure.</button>
                    <a href="{% url 'account-details' user.id %}" class="btn btn-secondary">No, I don't want to.</a>
                </form>
            </div>
        </div>
    </div>

{% include 'common/footer.html' %}
</body>
</html>

bookshelf/templates/accounts/edit_account.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Account</title>
    {% include 'common/link.html' %}
</head>
<body>
{% include 'common/nav.html' %}
<div class="container mt-5">
    <h2>Edit the Author</h2>

    <div class="card shadow-sm">
        <div class="card-body">
            <form method="post" >
                {% csrf_token %}

                <div class="form-group mb-3">
                    <label for="id_first_name">First Name</label>
                    <input type="text" class="form-control" id="id_first_name" name="first_name" value="{{ form.first_name.value }}" required>
                </div>

                <div class="form-group mb-3">
                    <label for="id_last_name">Last Name</label>
                    <input type="text" class="form-control" id="id_last_name" name="last_name" value="{{ form.last_name.value }}" required>
                </div>

                <div class="form-group mb-3">
                    <label for="id_date_of_birth">Email</label>
                    <input type="email" class="form-control" id="id_email" name="email"
                           value="{{ form.email.value }}" required>
                </div>

                <div class="form-group mb-3">
                    <label for="id_bio">Username</label>
                    <input type="text" class="form-control" id="id_username" name="username" value="{{ form.username.value }}">
                </div>

                <div class="form-group mb-3">
                    <label for="id_picture_url">Picture's url</label>
                    <input type="url" class="form-control" id="id_picture_url" name="picture_url" value="{{ form.picture_url.value }}">
                </div>


                <button type="submit" class="btn btn-success">Save Changes</button>
                <a href="" class="btn btn-secondary ml-2">Reject</a>
            </form>
        </div>
    </div>
</div>

{% include 'common/footer.html' %}
</body>
</html>

bookshelf/templates/accounts/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    {% include 'common/link.html' %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>
    {% include 'common/nav.html' %}    

    <div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header text-center" style="background-color: #908d8c">
                    <img src="{% static 'images/login.gif' %}" alt="LogIn" class="img-fluid mx-auto d-block" style="max-height: 80px; border-radius: 50px">
                </div>
                <div class="card-body">
                    {% if messages %}
                        <div class="alert alert-danger">
                            {% for message in messages %}
                                <p>{{ message }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="email">Username</label>
                            <input class="form-control" id="email" name="username" placeholder="Username">
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                        </div>
                        <button type="submit" class="btn btn-primary btn-block custom-button">Login</button>
                        <a href="{% url 'register' %}" class="btn btn-outline-secondary btn-block mt-2">Register</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

    
    {% include 'common/footer.html' %}
</body>
</html>

bookshelf/templates/accounts/logout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout</title>
    {% include 'common/link.html' %}
    <link rel="stylesheet" href="{% static 'css/logout.css' %}">
</head>
<body>
    {% include 'common/nav.html' %}
    <div class="container mt-5 d-flex justify-content-center">
        <div class="card" style="width: 400px;">
            <div class="card-header text-center" style="background-color: #908d8c;">
                <img src="{% static 'images/logout.gif' %}" alt="LogIn" class="img-fluid mx-auto d-block"
                     style="max-height: 80px; border-radius: 50px">
            </div>
            <div class="card-body text-center">
                <p>Are you sure you want to log out?</p>
                <div class="d-flex justify-content-center">
                    <a href="{% url 'logout' %}" class="btn btn-danger mr-2">Yes</a>
                    <a href="{% url 'home' %}" class="btn btn-secondary">No</a>
                </div>
            </div>
        </div>
    </div>

    
    {% include 'common/footer.html' %}
</body>
</html>

bookshelf/templates/accounts/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    {% include 'common/link.html' %}
    <link rel="stylesheet" href="{% static 'css/registration.css' %}">
</head>
<body style="padding-bottom: 70px;">
{% include 'common/nav.html' %}
<div class="container mt-5 d-flex justify-content-center mb-7">
    <div class="card" style="width: 400px;">
        <div class="card-header text-center" style="background-color: #908d8c;">
            <img src="{% static 'images/registration.gif' %}" alt="Register" class="img-fluid mx-auto d-block"
                 style="max-height: 80px; border-radius: 50px;">
        </div>
        <div class="card-body">
            <h5 class="card-title text-center mb-4">Create an Account</h5>
            <form method="post">
                {% csrf_token %}

                <div class="form-group text-center">
                    <label for="id_username">Username</label>
                    <p class="mb-0">{{ form.username }}</p>
                    {% if form.username.errors %}
                        <ul class="text-danger">
                            {% for error in form.username.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>

                <div class="form-group text-center">
                    <label for="id_email">Email</label>
                    <p class="mb-0">{{ form.email }}</p>
                    {% if form.email.errors %}
                        <ul class="text-danger">
                            {% for error in form.email.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>

                <div class="form-group text-center">
                    <label for="id_first_name">First Name</label>
                    <p class="mb-0">{{ form.first_name }}</p>
                    {% if form.first_name.errors %}
                        <ul class="text-danger">
                            {% for error in form.first_name.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>

                <div class="form-group text-center">
                    <label for="id_last_name">Last Name</label>
                    <p class="mb-0">{{ form.last_name }}</p>
                    {% if form.last_name.errors %}
                        <ul class="text-danger">
                            {% for error in form.last_name.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>

                <div class="form-group text-center">
                    <label for="id_password1">Password</label>
                    <p class="mb-0">{{ form.password1 }}</p>
                    {% if form.password1.errors %}
                        <ul class="text-danger">
                            {% for error in form.password1.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>

                <div class="form-group text-center">
                    <label for="id_password2">Confirm Password</label>
                    <p class="mb-0">{{ form.password2 }}</p>
                    {% if form.password2.errors %}
                        <ul class="text-danger">
                            {% for error in form.password2.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>

                <div class="d-flex justify-content-center">
                    <button type="submit" class="btn btn-primary btn-block w-100">Register</button>
                </div>
            </form>
        </div>
    </div>
</div>


{% include 'common/footer.html' %}
</body>
</html>